build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.23"
  amd64: "ghcr.io/home-assistant/amd64-base:3.23"
labels:
  org.opencontainers.image.title: "Home Assistant Enocean app"
  org.opencontainers.image.description: "Provide Home Assistant EnOcean compatibility using MQTT broker and integration"
  org.opencontainers.image.source: "https://github.com/ChristopheHD/HA_enoceanmqtt-addon"
  org.opencontainers.image.licenses: "GPL-3.0"
