---
name: CI

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/addon-ci.yaml@main
