---
name: CI

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  workflows:
    uses: home-assistant/addons-example/.github/workflows/lint.yaml@main
